### ISSUE TITLE
Unable connect as the client id is already in use. Retry with a unique client id.

### ISSUE THREAD

**Issue by yuanzhanghu** [pilwon/node-ib#27] opened 2016-02-17 02:56 UTC
Looks like we haven't sent clientId to IB gateway.

**Comment by lewisdawson** [comment] 2016-02-17 04:41
@yuanzhanghu I've successfully used multiple concurrent clients (with unique ids) to both TWS and IB Gateway. You might want to check to make sure you don't have a connection that's staying open and also make sure that if you're using multiple client ids, that they are indeed unique client ids.

**Comment by yuanzhanghu** [comment] 2016-02-19 00:04
Did you tried live account ?

**Comment by lewisdawson** [comment] 2016-02-19 03:40
@yuanzhanghu Do you mean my personal account as opposed to the demo account? If so, yes, I'm using my personal account.

**Comment by lewisdawson** [comment] 2016-02-19 04:24
@yuanzhanghu Alright, a regression was introduced in either 0.1.7 or 0.1.8. I see the same thing when I use 0.1.8, but it works fine in 0.1.6.
@ajpierce @yuanzhanghu @pilwon You guys have all made changes since 0.1.6. Can you guys have a look over your code to see if you introduced it?

**Comment by lewisdawson** [comment] 2016-03-16 06:40
@yuanzhanghu @ajpierce @pilwon Any ideas if one of your changes introduced this regression?

**Comment by ajpierce** [comment] 2016-03-17 11:47
@lewisdawson I think #20 is the most likely candidate, simply because it changed how we handle communication with the server.  Specifically, line 31 in `lib/socket.js`.  I bet if we split that back out into two calls, everything will work fine again.

**Comment by doronsh2000** [comment] 2016-10-14 07:54
Hi 

i'm on 0.1.12.  can't have more then 1 client connected (identified as client0)
using IB GW on Linux
changing the constructor to  clientId 6 didn't help. i see at the IB GW log
it reset the connection with clientId0 (it doesn't see the clientId 6 i set)

var ib = new (require('..'))({
   clientId: 6,
   host: '127.0.0.1',
   port: 4001
}).on('error', function (err) {

error i'm getting 

Unable connect as the client id is already in use. Retry with a unique client id.
read ECONNRESET

is there a problem in this version?

Thx
Doron

**Comment by doronsh2000** [comment] 2016-10-14 08:02
found issue with "single digit clientid".
when using 2 digits it's working fine. it seems that something in the code ignore/cut
first digit
what i see is when setting clientId to 12 , i can see IB GW identify it as clientId 2
what i see is when setting clientId to 16 , i can see IB GW identify it as clientId 6
thanks!

**Comment by claude2** [comment] 2017-02-09 09:43
This bug still exists in the latest version (v0.1.18). The first digit of the clientId is lost. If it was only one digits, it is considered 0. 

For example, for `clientId: 4` or `clientId: 20`, IB will consider clientId `0`. You can check that by calling reqOpenOrders, which will return existing orders from TWS only if clientId == 0, as explained [here](https://www.interactivebrokers.com/en/software/api/apiguide/java/reqopenorders.htm).

**Comment by lewisdawson** [comment] 2017-02-22 07:00
@pilwon @claude2 This is fixed by #54. The issue can be closed.

**Comment by pilwon** [comment] 2017-02-23 19:47
Awesome. Closing this issue.

**Closed by pilwon** 2017-02-23 19:47 UTC
