### ISSUE TITLE
Can i browserify this api (this is not an issue)

### ISSUE THREAD

**Issue by mallikarjundontamsetti** [pilwon/node-ib#35] opened 2016-04-27 12:30 UTC
Am completely new to the nodejs and javascript. My goal is to connect to the client side TWS/IB gateway through the web appp. Previously we used JNLP to connect to the client side TWS. Now you have given this wonderful library. And i try to browserify this to work on the client side. failed with some exception regarding net package. Is ther any way we can port this lib to browser side scripting.
Thanks in advance

**Comment by claude2** [comment] 2016-10-28 06:35
Using webpack you can avoid that exception, `Cannot resolve module 'net'`, just set node.net to `empty` as shown [here](https://github.com/request/request/issues/1529#issuecomment-103454943).

But there is a new problem after you do that:

> Uncaught (in promise) Error: Cannot find module './contract'.

It is caused by [this line](https://github.com/pilwon/node-ib/blob/master/lib/index.js#L389).

@pilwon, any plans to use modern ES6 modules?

**Comment by pilwon** [comment] 2016-10-28 12:15
Closing this issue. Please follow #76.

**Closed by pilwon** 2016-10-28 12:15 UTC
